In [20]:
import pandas as pd
import geopandas as gpd

In [4]:
df_stop1 = pd.read_csv('stop1.csv')

In [5]:
df_allstop = pd.read_csv('allstop.csv')

In [7]:
df_stop1['Stop'] = df_stop1['Stop'].str.lower()

In [10]:
df_allstop['stop_name'] = df_allstop['stop_name'].str.lower()

In [11]:
df_M12_Stop = df_stop1.merge(df_allstop, left_on='Stop', right_on='stop_name', how='left')

In [12]:
df_M12_Stop

,Stop,Unnamed: 1,Unnamed: 2,stop_id,stop_name,stop_desc,stop_lat,stop_lon
0,8 av/w 12 st,NaN,NaN,405452.0,8 av/w 12 st,NaN,40.737903,-74.004356
1,w 14 st/8 av,NaN,NaN,401575.0,w 14 st/8 av,NaN,40.739511,-74.002172
2,w 14 st/8 av,NaN,NaN,403897.0,w 14 st/8 av,NaN,40.740027,-74.002966
3,w 14 st/9 av,NaN,NaN,405265.0,w 14 st/9 av,NaN,40.741148,-74.005521
4,w 14 st/10 av,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,11 av/w 15 st,NaN,NaN,405157.0,11 av/w 15 st,NaN,40.743388,-74.008400
6,11 av/ w 18 st,NaN,NaN,405531.0,11 av/ w 18 st,NaN,40.745731,-74.007993
7,w 24 st/11 av,NaN,NaN,404926.0,w 24 st/11 av,NaN,40.749997,-74.007489
8,12 av/ w 27 st,NaN,NaN,405455.0,12 av/ w 27 st,NaN,40.752215,-74.007578
9,12 av/w 30 st,NaN,NaN,405456.0,12 av/w 30 st,NaN,40.754840,-74.006232
10,12 av/w 33 st,NaN,NaN,405457.0,12 av/w 33 st,NaN,40.756398,-74.005125
11,12 av/ w 40 st,NaN,NaN,405458.0,12 av/ w 40 st,NaN,40.760765,-74.001924
12,12 av/w 43 st,NaN,NaN,402160.0,12 av/w 43 st,NaN,40.762552,-74.000157
13,12 av/w 46 st,NaN,NaN,402161.0,12 av/w 46 st,NaN,40.764287,-73.998337
14,12 av/w 46 st,NaN,NaN,403956.0,12 av/w 46 st,NaN,40.764460,-73.998687
15,12 av/w 48 st,NaN,NaN,402162.0,12 av/w 48 st,NaN,40.765583,-73.997431
16,12 av/w 52 st,NaN,NaN,405459.0,12 av/w 52 st,NaN,40.768082,-73.995597
17,12 av/w 55 st,NaN,NaN,405460.0,12 av/w 55 st,NaN,40.769942,-73.994246
18,w 57 st/11 av,NaN,NaN,402205.0,w 57 st/11 av,NaN,40.770230,-73.991334
19,w 57 st/10 av,NaN,NaN,403986.0,w 57 st/10 av,NaN,40.769323,-73.988953
20,w 57 st/10 av,NaN,NaN,403992.0,w 57 st/10 av,NaN,40.768866,-73.988149
21,w 57 st/9 av,NaN,NaN,402233.0,w 57 st/9 av,NaN,40.768068,-73.985902
22,w 57 st/9 av,NaN,NaN,403984.0,w 57 st/9 av,NaN,40.767697,-73.985340
23,8 av/w 57 st,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,w 58 st/broadway,NaN,NaN,405299.0,w 58 st/broadway,NaN,40.767155,-73.981981
25,w 58 st/broadway,NaN,NaN,803008.0,w 58 st/broadway,NaN,40.767088,-73.981842

In [13]:
df_M12_Stop = df_M12_Stop[df_M12_Stop.stop_id != 403956.0]

In [14]:
df_M12_Stop = df_M12_Stop[df_M12_Stop.stop_id != 803008.0]

In [16]:
df_M12_Stop.to_csv('df_M12_Stop_1.csv')

In [17]:
df_stop2 = pd.read_csv('stop2.csv')
df_stop2['Stop'] = df_stop2['Stop'].str.lower()
df_M12_Stop2 = df_stop2.merge(df_allstop, left_on='Stop', right_on='stop_name', how='left')

In [19]:
df_M12_Stop2.to_csv('df_M12_Stop_2.csv')